; PlatformIO project config — ESP32_MasterFanServer
; Плата: ESP32-C3 mini

[env:esp32c3]
platform = espressif32
board = esp32-c3-devkitm-1
framework = arduino
monitor_speed = 115200
; PlatformIO сам определяет порт при аплоаде/мониторе — ничего выбирать руками не надо

lib_deps =
    knolleary/PubSubClient @ ^2.8
    paulstoffregen/OneWire @ ^2.3.7
    milesburton/DallasTemperature @ ^3.11.0